version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # default location of `.github/workflows`
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "nuget"
    directory: "/portainer-monitor-addon/source"
    schedule:
      interval: "weekly"
